config/routes.rb
Atomic::Application.routes.draw do
  root to: "rooms#index"
  resources :rooms do
    resources :messages
  end
  resources :messages
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :content, :room_id
  belongs_to :room
end

app/models/room.rb
class Room < ActiveRecord::Base
  include Redis::Objects

  has_many :messages
  attr_accessible :name, :max_messages
  attr_accessor :non_atomic

  counter :messages_requested
  counter :messages_posted

  def requested_channel
    [id, 'requested'].join("-")
  end

  def posted_channel
    [id, 'posted'].join("-")
  end

  def chat_channel
    [id, 'chat'].join("-")
  end

  def send_to_pubnub(channel, message)
    $pubnub.publish(channel: channel, message: message, callback: ->(m) {Rails.logger.info(m)})
  end

  def send_message_to_requested_channel(message)
    send_to_pubnub(requested_channel, message)
  end

  def send_message_to_posted_channel(message)
    send_to_pubnub(posted_channel, message)
  end

  def send_message_to_chat_channel(message)
    send_to_pubnub(chat_channel, message)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
  end

  def show
    @message = Message.find(params[:id])
  end

  def index
    # This only makes sense in the context of a room
    @room = Room.find(params[:room_id])
    @messages = @room.messages
  end

  def create
    @room = Room.find(params[:message][:room_id])
    @message = Message.new(params[:message])

    if params[:non_atomic]
      logger.info "Non-Atomic Create"
      non_atomic_create
    else
      logger.info "Atomic Create"
      atomic_create
    end
  end

  private
  # This block is the atomic operation, we are altering
  # the messages_requested count and evaluating it's value
  # at the same time
  def atomic_create
    @room.messages_requested.increment do |messages_requested|
      @room.send_message_to_requested_channel(messages_requested)
      if messages_requested <= @room.max_messages
        @room.messages_posted.increment
        @room.send_message_to_posted_channel(@room.messages_posted.value)
        if @message.save
          @room.send_message_to_chat_channel(render_message_to_string)
          render nothing: true
        else
          logger.info @message.errors.inspect
        end
      else
        render nothing: true
      end
    end
  end

  # This is non-atomic, concurrent users can and will retrieve
  # the same count for messages_posted
  # they will get through and violate the max_messages rule
  #
  # * if you place a lock (via lock: true, or .transaction do) on @room,
  # you will not be able to modify
  # that room while people are posting messages, which is undesirable
  # in most applications
  def non_atomic_create
    messages_requested = @room.messages_requested.increment
    @room.send_message_to_requested_channel(@room.messages_requested.value)
    if @room.messages_posted <= @room.max_messages
      if @message.save
        @room.messages_posted.increment
        @room.send_message_to_posted_channel(@room.messages_posted.value)
        @room.send_message_to_chat_channel(render_message_to_string)
        render nothing: true
      else
        logger.info @message.errors.inspect
      end
    else
      render nothing: true
    end
  end

  def render_message_to_string
    render_to_string(partial: '/messages/message', layout: false, locals: {message: @message})
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def new
    @room = Room.new
  end

  def show
    @room = Room.find(params[:id])
  end

  def index
    @room = Room.new
    @rooms = Room.all
  end

  def create
    @room = Room.new(params[:room])
    if @room.save
      redirect_to room_url(@room), notice: "Your room has been created! Start Chatting."
    else
      flash[:alert] = "Unable to save that room"
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title AoR Atomic Demo
    meta name="description" content="A demonstration showing atomicity being respected in an application."
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = yield :head
  body
    .container
      = yield
    = yield :page_bottom

app/views/messages/_message.html.slim
li.media.message
  .media-body
    .media-heading
      = l(message.created_at)
    = message.content.html_safe

app/views/messages/index.html.slim
#chat
  ul.media-list= render @messages

app/views/messages/show.html.slim
= render @message

app/views/rooms/_room.html.slim
li.room
  - if non_atomic
    = link_to room.name, room_url(room, non_atomic: true)
  - else
    = link_to room.name, room_url(room)
  

app/views/rooms/index.html.slim
- unless @rooms.empty?
  .row
    .span12
      h1 Lobby
    .span6
      h2 Atomic
      #rooms-atomic
        ul.nav.nav-tabs.nav-stacked
          = render partial: '/rooms/room', collection: @rooms, locals: {non_atomic: false}
    .span6
      h2 Non-Atomic
      #rooms-non-atomic
        ul.nav.nav-tabs.nav-stacked
          = render partial: '/rooms/room', collection: @rooms, locals: {non_atomic: true}
.row
  .span6.offset4
    h2 Create A New Room
    = form_for @room do |f|
      = f.label :name, "Room Name"
      = f.text_field :name
      = f.label :max_messages, "Maximum Messages Allowed"
      = f.number_field :max_messages
      .controls
        = f.submit "Add Room", class: 'btn btn-primary btn-large'

app/views/rooms/show.html.slim
= content_for :head do
  script src='http://cdn.pubnub.com/pubnub-3.5.3.min.js'

= content_for :page_bottom do
  javascript:
    (function(){
      var pubnub = PUBNUB.init({ 'subscribe_key' : 'sub-c-b8f67c24-f34b-11e2-a11a-02ee2ddab7fe' });

      pubnub.subscribe({
        channel: "#{@room.requested_channel}",
        message: function(m) {
          $('#messages_requested').text(m);
        },
        presence: function(message, event, channel) {
          // console.log("Channel: ", channel);
          // console.log("Join/Leave/Timeout: ", message.action);
          // console.log("Occupancy: ", message.occupancy);
          // console.log("User ID: ", message.uuid);
          $('#connected').text(message.occupancy);
        }
      });

      pubnub.subscribe({
        channel: "#{@room.posted_channel}",
        message: function(m) {
          $('#messages_posted').text(m);
        }
      });

      pubnub.subscribe({
        channel: "#{@room.chat_channel}",
        message: function(m) {
          $('#messages').append(m);
        }
      });
    })();

ul.breadcrumb
  li
    = link_to "Back To Lobby", rooms_url
    span.divider= "/"
  li.active= @room.name
- if params[:non_atomic]
  = link_to "Go To Atomic Version", room_url(@room), class: 'btn', style: 'margin-bottom: 1em;'
  .alert.alert-error This room does not add messages atomically, the maximum messages limit can be violated
- else
  = link_to "Go To Non-Atomic Version", room_url(@room, non_atomic: true), class: 'btn', style: 'margin-bottom: 1em;'

.hero-unit style='text-align: center;'
  p Scan this with a qr code reader to join:
  = image_tag("https://chart.googleapis.com/chart?cht=qr&chs=300x300&chl=#{request.url}&chld=H|0")
  h1 Welcome to #{@room.name}

ul#messages.media-list
  = render partial: '/messages/message', collection: @room.messages

= form_for @room.messages.build do |f|
  - if params[:non_atomic]
    = hidden_field_tag :non_atomic, true
  = f.hidden_field :room_id, value: @room.id
  .row
    .span3
      .well
        h4 Connections:
        span#connected.badge.badge-info 1
    .span3
      .well
        h4 Requested:
        span#messages_requested.badge.badge-success= @room.messages_requested.value
    .span3
      .well
        h4 Posted:
        span#messages_posted.badge.badge-info= @room.messages_posted.value
    .span3
      .well
        h4 Limit:
        span#max_messages.badge.badge-important= @room.max_messages

  = f.text_field :content, class: 'chat-input'
  .controls
    = f.submit "Post Message", class: 'btn btn-primary btn-large'